"""
Scenario 5 — six-month timing and committee-allocation sensitivity
==================================================================
CLAIM BOUNDARY:
This script does not estimate a real-world probability for NCRI, MEK, or any
other political organization. It evaluates consequences of explicit synthetic
assumptions.

Part A asks what fraction of an assumed lognormal election-timing distribution
falls within six months.

Part B asks what committee-share distribution follows IF one organization is
assigned an arbitrary leverage parameter. Because leverage is inserted into
the probability weights by construction, a resulting share above equal-weight
20% is NOT independent evidence of dominance.

Important statistical note:
For numpy's lognormal distribution, exp(mu) is the MEDIAN, not the arithmetic
mean. The old variable name MEAN_ELECTION_MONTHS was misleading.
"""
import json
from pathlib import Path

import numpy as np

CLAIM_LABEL = "hypothesis"
RNG_SEED = 45
rng = np.random.default_rng(RNG_SEED)

N_TRIALS = 2000

# Part A — timing. ARBITRARY scenario assumptions.
LOGNORMAL_ELECTION_MEDIAN_MONTHS = 14
LOGNORMAL_ELECTION_SIGMA = 0.45
DEADLINE_MONTHS = 6

# Part B — committee allocation. ARBITRARY scenario assumptions.
N_COMMITTEES = 25
N_MEMBER_ORGS = 5
EQUAL_WEIGHT_SHARE = 1 / N_MEMBER_ORGS
DOMINANT_ORG_LEVERAGE = 0.35


def simulate_election_timing():
    return rng.lognormal(
        mean=np.log(LOGNORMAL_ELECTION_MEDIAN_MONTHS),
        sigma=LOGNORMAL_ELECTION_SIGMA,
    )


def allocation_weights():
    raw = np.array(
        [EQUAL_WEIGHT_SHARE + DOMINANT_ORG_LEVERAGE]
        + [EQUAL_WEIGHT_SHARE * (1 - DOMINANT_ORG_LEVERAGE / 4)] * 4,
        dtype=float,
    )
    return raw / raw.sum()


def simulate_committee_allocation():
    assignments = rng.choice(
        N_MEMBER_ORGS,
        size=N_COMMITTEES,
        p=allocation_weights(),
    )
    return float((assignments == 0).mean())


if __name__ == "__main__":
    election_times = np.array([simulate_election_timing() for _ in range(N_TRIALS)])
    fraction_on_time = float((election_times <= DEADLINE_MONTHS).mean())

    dominant_shares = np.array(
        [simulate_committee_allocation() for _ in range(N_TRIALS)]
    )
    mean_dominant_share = float(dominant_shares.mean())
    fraction_majority = float((dominant_shares > 0.5).mean())

    print("Scenario 5 — synthetic timing/allocation sensitivity")
    print(f"claim_label: {CLAIM_LABEL}")
    print(f"timing median assumed: {LOGNORMAL_ELECTION_MEDIAN_MONTHS} months")
    print(f"timing sigma assumed: {LOGNORMAL_ELECTION_SIGMA}")
    print(f"fraction election <= 6 months: {fraction_on_time:.3f}")
    print(f"arbitrary leverage parameter: {DOMINANT_ORG_LEVERAGE:.3f}")
    print(f"resulting normalized allocation weights: {allocation_weights().tolist()}")
    print(f"mean modeled share for indexed organization: {mean_dominant_share:.3f}")
    print(f"fraction modeled majority share: {fraction_majority:.3f}")
    print(
        "Interpretation: these outputs are generated by the stipulated timing "
        "and allocation assumptions; they are not measurements of a real organization."
    )

    results = {
        "schema": "twelve-gates/scenario5-timing-allocation-sensitivity/v2",
        "claim_label": CLAIM_LABEL,
        "not_empirical_validation": True,
        "n_trials": N_TRIALS,
        "election_deadline_months": DEADLINE_MONTHS,
        "lognormal_election_median_months_assumed": LOGNORMAL_ELECTION_MEDIAN_MONTHS,
        "lognormal_election_sigma_assumed": LOGNORMAL_ELECTION_SIGMA,
        "simulated_mean_election_months": float(election_times.mean()),
        "fraction_election_on_time": fraction_on_time,
        "n_committees": N_COMMITTEES,
        "n_member_orgs": N_MEMBER_ORGS,
        "equal_weight_share": EQUAL_WEIGHT_SHARE,
        "dominant_org_leverage_assumed": DOMINANT_ORG_LEVERAGE,
        "normalized_allocation_weights": allocation_weights().tolist(),
        "mean_modeled_indexed_org_share": mean_dominant_share,
        "fraction_modeled_majority_share": fraction_majority,
        "seed": RNG_SEED,
        "interpretation_boundary": (
            "Conditional synthetic sensitivity output. The leverage and timing "
            "parameters are arbitrary scenario assumptions, not empirical estimates."
        ),
    }
    output_dir = Path(__file__).resolve().parent / "results"
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / "scenario5_results_v2.json"
    out.write_text(json.dumps(results, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"saved: {out}")
